### ISSUE TITLE
Filter: Add an `EXISTS` operator

### ISSUE THREAD

**Issue by gmourier** [meilisearch/product#22]
## Description

The introduction of the new search engine in v0.21.0 allows us to introduce several new operators that might give users new filtering capabilities.

One of them could be the handling of the following filters during the search:

- `price NOT EXISTS` which means `all the documents that do NOT contain the field price`.
- `price EXISTS` alone, which means `all the documents that contain the field price`, no matter the value or the type.

### Discussions
#88

**Comment by loiclec** [comment]
I have drafted an implementation of this operator on the branches `filter/field-exist` and `filter/field-exist-alt-syntax` of the “milli” repo.

The behaviour of the filter is fairly straightforward, but I wanted to share a few observations.

## 1. When the attribute's value is an empty array
The following document:
````json
{
	"id": 2,
	"size": []
}
````
will currently NOT be included by the filter `size` (or `size EXISTS`, depending on the syntax we adopt).

The reason is that the filter is implemented as:
> Retrieve all the documents whose `size` attribute contains ANY value

which is technically the most straightforward way to implement the filter.

It is debatable whether that is the correct choice, but note that other operators also behave similarly. For example, the above document will also not be included by the filter:
````
NOT size = 34 
````
because `NOT size = 34` is simplified to `size != 34` which means “`size` exists and its value is different from 34”. Whether `NOT` should behave that way can also be discussed separately.

## 2. Syntax

The proposed syntax for this filter has been to simply write the name of the attribute that should contain a value. However, I am a a little opposed to it for a couple of reasons:

* The filter is not self-explanatory and difficult to name. I think we should try to create a syntax that is as explicit as possible. If someone encounters a problem with this filter, they can create an issue titled “problem with EXISTS filter”. On the other hand, I find it difficult to refer to this filter if there is no keyword for it.

* I am afraid that it will be more difficult to evolve the grammar and improve error reporting later on. It is rather nice in the current filter grammar that an attribute's name is not a valid filter in itself. So that when we see the invalid filter `colour green`, we can say “there should be something following `colour`, we were expecting a `=`, `>`, etc. (other math operators)”.  Now the list of suggestions is already bigger, since, for example, `colour AND green` is also a valid filter.
  Note that at the moment, the addition of this filter does not cause any immediate problem except for a drop in the quality of error reporting (which can probably be improved), but I am slightly worried about the future. 

On the other hand, choosing a name can also be tricky. If we choose “colour EXISTS”, then it is possible to misinterpret it as “the field colour exists“ instead of the more correct “there exists a value in the field colour”.

## 3. Other
Note that the filter `colour EXISTS` can already be expressed using the filter:
````
colour = 0 OR colour != 0
````
However, there is no equivalent to the filter `NOT colour EXISTS`.

I looked up what syntax Algolia and Typesense use, but it seems that they do not have an equivalent filter (correct me if I am wrong).
Algolia Documentation: https://www.algolia.com/doc/api-reference/api-parameters/filters/
Typesense Documentation: https://typesense.org/docs/0.22.2/api/documents.html#search-parameters


### Recap

I had two questions:

1. Are we okay with the behaviour of this filter when an attribute has an empty array as value?
2. Should the syntax be:
	* `value` / `NOT value`
	* `value EXIST` / `NOT value EXIST`
	* `value EXISTS` / `NOT value EXISTS`
	* something else?

**Comment by irevoire** [comment]
There is also something I don't like about the postfix `EXIST`; it's that people will probably want to write `field NOT EXIST` instead of `NOT field EXIST`.
It would be nice if we found a prefixed version of the thing. Maybe `EXIST value` / `NOT EXIST value` is enough?

**Comment by gmourier** [comment]
Hi @loiclec 👋

Thank you for this information. 

1. Does `EXISTS` can be used to know if a field exists for a document, not necessarily checking for a value? 

E.g. using `size EXISTS` will return

```jsonc
{
    "id": 1,
    "size": [] 
}
```

while

```json
{
    "id": 1,
    ...
```

won't be returned.

Today, it is not possible to use the syntax `size = null` to retrieve a document that has a size field set to nothing akka a `null` marker.

Having `EXISTS` and `NULL` / `EMPTY` could permit to filter on both.

- `EXISTS` checks that the key exists regardless of the value. The fact that `size != 34` returns documents without the size field and documents with size set to something other than 34 seems logical to me. Using `size EXISTS AND size != 34` could be used to add precision to the result set and only selects those where `size` really exists.
- `NULL` allows checking that the value is `null` for an existing field. `[]`, `""` are not considered `null`.
- `EMPTY` allows checking that the value is  "empty" for an existing field.  In this case, `null` is also considered as an empty value with `[]`, and `""`.

2. Personally, I'm all for `value EXISTS` / `NOT value EXISTS` given all the propositions since it's closer to the SQL `EXISTS` keyword.

My answer to 1. does not directly answer the question but raises the idea of introducing more granular filters to allow a user to manipulate and manage his documents. (We may add `filter` on the `/documents` endpoint in the future, it would make sense, especially for document deletion from a query)

**Comment by loiclec** [comment]
Hi @gmourier 👋 

For now, it's not possible to use `EXISTS` to return documents whose attribute is `null` / `[]`. 

During indexing, for each attribute, milli precomputes the list of documents that have a value (number or string) for this attribute. As far as I understand, it is essential to do so for performance reasons. For example, given the documents:
```json
{ "id": 1, "colour": "green" }
{ "id": 2, "colour": null, "size": [2]  }
{ "id": 3, "colour": ["blue", 2], "size": "large"  }
```
Then the result of that precomputation will be, more-or-less:
```yaml
{
    "colour": {
        "ids_containing_numbers": [3],
        "ids_containing_strings": [1, 3]
    },
    "size": {
        "ids_containing_numbers": [2],
        "ids_containing_strings": [3]
    }
}  
```
This is the information that is used to determine which documents satisfy `colour EXISTS`.  To be able to quickly recover the documents with a NULL or EMPTY attribute, we would have to modify that precomputation phase and store additional information. I don't have a solid grip on what it would take to do so or the tradeoffs that are involved. Maybe @Kerollmops can confirm if what I said is accurate and weigh in on the question. 

--- 

> EXISTS checks that the key exists regardless of the value. The fact that size != 34 returns documents without the size field and documents with size set to something other than 34 seems logical to me. Using size EXISTS AND size != 34 could be used to add precision to the result set and only selects those where size really exists.

Personally, I agree with you. It would make sense to change the meaning of `size != 5` to be “return documents without a size field or with a value different than 5”. This would, IMO, solve an inconsistency with the `NOT` operator, which is that the filter `A OR NOT A` does not mean “select all documents”. I find that surprising. For example:
```
colour = green OR NOT colour = green
```
is internally transformed to:
```
colour = green OR colour != green
```
which is equivalent to
```
colour EXISTS
```

There are two ways to solve this inconsistency:
1. As mentioned earlier, change the meaning of `NOT size = 5` and/or `size != 5` so that it also returns documents without a `size` field. This is made possible by the addition of the EXISTS/NULL/EMPTY operators.
2. Change the meaning/implementation of NOT so that **by definition** a document is either selected by the filter `A` xor by `NOT A`. 

I am bringing this up now because it is related to this issue. But it may be worth opening a new discussion about `NOT` separately.

**Comment by Kerollmops** [comment]
> For now, it's not possible to use `EXISTS` to return documents whose attribute is `null` / `[]`.

We can modify [the `number/string_faceted_documents_ids` functions (and rename them)](https://github.com/meilisearch/milli/blob/582930dbbb146ff7522893856fc805f787e13b8e/milli/src/index.rs#L725-L741) to also store the documents ids of the documents that contains the field but without any value:

```json
{ "id": 2, "colour": null, "size": []  }
```

> During indexing, for each attribute, milli precomputes the list of documents that have a value (number or string) for this attribute. As far as I understand, it is essential to do so for performance reasons. For example, given the documents:
> 
> [...]
> 
> This is the information that is used to determine which documents satisfy `colour EXISTS`. To be able to quickly recover the documents with a NULL or EMPTY attribute, we would have to modify that precomputation phase and store additional information. I don't have a solid grip on what it would take to do so or the tradeoffs that are involved. Maybe @Kerollmops can confirm if what I said is accurate and weigh in on the question.

To be able to retrieve the documents that contain the field but this field is known to be empty or null we would require a new database, akin to the previously described one, and as @loiclec said: we need to add a little bit more information into the indexing phase but that doesn't seem impossible nor difficult.

**Comment by irevoire** [comment]
> This would, IMO, solve an inconsistency with the NOT operator, which is that the filter A OR NOT A does not mean “select all documents”.

I get the idea, and I'm not particularly against it. It would effectively get rid of some inconsistencies in the syntax.
Now the real question is, does it matter? The people who use meili are looking for the easiest syntax that will do what they want as easily as possible.

If you have a mixed database with things like that for example;
```json
{ "id": 1, "product": "T-shirt",                  "size": "S",         "color": "yellow" }
{ "id": 2, "product": "Hedgehog plush",  "size": "30cm"                             }
{ "id": 3, "product": "Kitchen cabinet",                             "color": "pink"    }
```

If I write `size != S` in most applications I would expect the shirt and hedgehog to be returned :thinking: 
At least I can't think any use-case where that's not the case but if you got one I would love to hear about it.
And also tbh I don't think what I did is a _big_ use case because *I hope* everyone in this situation would write something like that `product = "T-shirt" AND size != S` and in this case, it would work.

The other case that may be more common actually is with dataset where you have missing data for some products;
```json
{ "id": 1, "product": "T-shirt", "size": "S", "color": "yellow" }
{ "id": 1, "product": "T-shirt", "size": "M", "color": "yellow" }
{ "id": 1, "product": "T-shirt", "size": "L", "color": "yellow" }
{ "id": 1, "product": "T-shirt", "color": "yellow" }
```
Is it expected to return the T-shirt with no properties? I would say no.

-------

And now about the inconsistencies, it works well with « math » operators but it actually doesn't work so well with the geo operator.
If I say « Hey I want all the documents in the following radius around this point » or « I want all the documents that are NOT in this radius » I'm in no way asking for the documents that do not contains a geo point.

**Comment by gmourier** [comment]
> If I write size != S in e-commerce applications I would expect the shirt and hedgehog to be returned 

Agreed! But I think you have to look at it the other way around, what will happen in most cases is that users will select other sizes than `S` via a facets interface.

I _imagine_ those operators being most useful for managing documents on `/documents` if the `filter` parameter is exposed on them (I'm thinking of delete by query feature) more than at search time.

**Comment by gmourier** [comment]
A pull-request specification is in review https://github.com/meilisearch/specifications/pull/163.

**Comment by gmourier** [comment]
Closed since [specified](https://github.com/meilisearch/specifications/pull/163) and planned for `v0.29` release.
