### ISSUE TITLE
Manually update Meilisearch version

### ISSUE THREAD

**Issue by qdequele** [meilisearch/product#365]
# **Problem statement**

As a user, I expect to be able to use the latest version of MeiliSearch at all times. I also expect to be able to migrate all my projects to the latest version of MeiliSearch. 

# Solution

Add a button in a project that allows users to update the MeiliSearch version. 

### Backend side

First, we will need to attach a new volume to each pod. This new volume dedicated to the dumps will have only 1Gb of data. We will also have to add [the environment variables](https://docs.meilisearch.com/reference/features/configuration.html#dumps-destination ) dedicated to the dumps to each MeiliSearch. 

Without going into the technical details of each operation, here is the sequence of events that will occur during a MeiliSearch update. 

1. Receive the update request. Put the server in "updating" status.
2. Modification of the proxy to prohibit requests with a POST/PUT/PATCH/DELETE header. 
3. Change on the fly the volume dedicated to the dumps for a volume with the size of the data volume. 
4. [Initiate a dump](https://docs.meilisearch.com/reference/api/dump.html#create-a-dump) on MeilISearch.
5. Do long polling to know when the dump is finished. This can be done every 5 seconds. 
6. Launch a new pod with the latest version of MeiliSearch. Attach the previously used update volume to it. Do not forget to add the environment variable to ingest a dump. 
7. Do some long poling on the health route to know when the machine is up and ready to be used. This can be done every 10 seconds for the first 5 minutes. Every 30 seconds thereafter.
8. Once the new pod is ready, change the proxy and redirect all traffic from the old pod to the new one. Autoregister all requests, including the new one.
9. Set the server to "active" status. 
10. Delete the old pod but do not delete the update volume attached to it. It is still in use on the new pod.
11. Change the dump volume of the new pod by a volume with 1Gb of data. Delete the old dump volume.  

Every step should be written and updated somewhere. 
If an error occurred during this process trigger an error status, then revert all actions. 

### Limitations

During the update, the project will continue to answer all search requests but will not be able to process any modifications. Every PUT/POST/PATCH/DELETE HTTP route will return a maintenance error code. 

It's theatrically impossible to estimate the time the update will take. It could be seconds or hours. 

### Future improvements
- Use S3 to store dumps instead of a volume. 
- Add logs during a dump import in MeilISearch to be able to know where we are in the process. 
- Add a better interface that shows the process and where we are in it. 

# Todo
### Design
- [x] https://github.com/meilisearch/tmp-public-release-cloud/issues/2

### Dev
- [x] https://github.com/meilisearch/meilisearch-cloud/issues/420

**Comment by qdequele** [comment]
Link to feature: https://meilisearch.productboard.com/feature-board/planning/features/11071610

**Comment by qdequele** [comment]
@tpayet @nicolasvienot, is it enough for starting the proof of concept on this feature?

**Comment by gmourier** [comment]
@qdequele We should also block PATCH requests since we have them for API Keys since v0.25.0 🤓

**Comment by qdequele** [comment]
Good point @gmourier :)

**Comment by nicolasvienot** [comment]
I have a few questions/comments about the volumes

- We should clearly name here the different volumes like `storage volume` and `update volume`
- In `3.` you say `Change on the fly the volume dedicated to the dumps for a volume with the size of the data volume`, do you mean keep the same volume but resizing it from `1gb` to `the storage size of the project` ?
- If I understood, the `storage volume` of `pod old version` will be deleted and a new one will be created for `pod new version` when we create it. The `update volume` will be transferred from `pod old version` to `pod new version`, when the update is done it will be deleted and then a new one of `1gb` will be created (which is nice because we can't decrease the size of a volume). Am I right?
- I think this might be easier to create the volume before we initiate the dump. This would also mean not creating an `update volume` for each pod but only when a user needs an update. What could be done is:
  - Set `MEILI_DUMPS_DIR` to `update-volume/dumps`
  - Before initiating the dump, we would create the `update volume` and link it to the `pod old version` by adding a `mountPath: /update-volume`
  - When it's done, we launch the dump, transfer the `update volume` to the `pod new version`, launch it, and when everything is updated we delete the  `update volume`

About the wording for Kubernetes, we should make the difference between a `pod` and a `statefulset`.
Each project is a `statefulset` that creates a `pod`, a `persistent volume claim`, a `service` and an `ingress`. If the `pod` is down, the `statefulset` will create a new one with the same configuration and using the same `volume`.
In our case, we will work in the pod to do the dump, use a new pod to recreate the `data.ms` etc. but we will probably create a new `statefulset` for the updated instance of MeiliSearch (to ensure we won't lose any data in the process).
This is also something to be thought, we could consider using the same `statefulset` but to change its configuration as long as we are sure that we can go back and not lose the data (for example changing in the configuration the MeiliSearch version, the flag to use the dump and use a different volume to not erase the data from the previous, relaunch it so it will create a new pod with the new configuration)

- We will need to block the route POST `/dumps` to ensure a user can't create a dump by himself (not done yet)

I'm available to talk about the previous comments. We will need to think through the process with @eskombro, but I think this is clear enough to start a POC and get back to you with the issues we might encounter 😄

**Comment by eskombro** [comment]
I agree with the process in general, but would like to add a few precisions/questions

> Modification of the proxy to prohibit requests with a POST/PUT/PATCH/DELETE header.

We need to be careful since the search requests can be, and often are, POST requests. This exception should be handled if we want to keep alive the search functionality during the process to reduce downtime.

> Once the new pod is ready, change the proxy and redirect all traffic from the old pod to the new one. Autoregister all requests, including the new one.

We will modify the Kubernetes Ingress as soon as the pod is up and running, meaning that the dump has been ingested and indexation is done. I am not sure I understand what  "Autoregister all requests, including the new one" means, can you clarify a little bit please @qdequele 

>  I think this might be easier to create the volume before we initiate the dump. This would also mean not creating an update volume for each pod but only when a user needs an update. 

@nicolasvienot  I agree with this, creating a volume is quite fast and can be done on request for an update. I would suggest:
- Modifying the `3` to 'Create a volume and attach it to the pod that is going to be updated'. We don't need to create an `update` volume for each Statefulset.
- When the update process is in progress, a new Statefulset will be created with the required Volume. This volume will be kept for the new instance.
- The `10` point would be Deleting the old pod, it's volume, AND the update volume. 
- Finally `11` wouldn't be necessary and can be deleted.

> If an error occurred during this process trigger an error status, then revert all actions.

If an error occurred, in this new scenario, we would just delete the update volume, the new pod, and remove the firewall rules that reject requests, and the old pod would continue working as before.
